name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Ensure submodules are checked out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t pycity_scheduling:latest .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Ensure submodules are checked out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run examples/example_00_fundamentals.py in Docker container
        run: |
          docker run --rm pycity_scheduling:latest /bin/bash -c "
          scip --version &&
          gurobi_cl --version &&
          python3 /opt/pycity_scheduling/examples/example_00_fundamentals.py"
